version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - mq_net
    
  ibmmq:
    image: icr.io/ibm-messaging/mq:latest
    environment:
      LICENSE: accept
      MQ_QMGR_NAME: QM1
      MQ_APP_PASSWORD: passw0rd
      MQ_ADMIN_PASSWORD: passw0rd
    volumes:
      - qm1data:/mnt/mqm
    ports:
      - "1414:1414"
      - "9443:9443"
    networks:
      - mq_net
volumes:
  qm1data:

networks:
  mq_net:
    driver: bridge